// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: calendars.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkCurriculumExists = `-- name: CheckCurriculumExists :one
SELECT id FROM curricula WHERE id = $1 AND is_active = true
`

func (q *Queries) CheckCurriculumExists(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, checkCurriculumExists, id)
	err := row.Scan(&id)
	return id, err
}

const checkSubjectBelongsToCurriculum = `-- name: CheckSubjectBelongsToCurriculum :one
SELECT id FROM subjects WHERE id = $1 AND curriculum_id = $2 AND is_active = true
`

type CheckSubjectBelongsToCurriculumParams struct {
	ID           pgtype.UUID `json:"id"`
	CurriculumID pgtype.UUID `json:"curriculum_id"`
}

func (q *Queries) CheckSubjectBelongsToCurriculum(ctx context.Context, arg CheckSubjectBelongsToCurriculumParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, checkSubjectBelongsToCurriculum, arg.ID, arg.CurriculumID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const claimCalendar = `-- name: ClaimCalendar :one
UPDATE calendar_links
SET owner_id = $2, ttl_expires_at = $3, updated_at = NOW()
WHERE id = $1 AND owner_id IS NULL
RETURNING id, slug, owner_id, name, description, is_public, access_count, last_accessed_at, ttl_expires_at, created_at, updated_at, lang, format_event_titles
`

type ClaimCalendarParams struct {
	ID           pgtype.UUID        `json:"id"`
	OwnerID      pgtype.UUID        `json:"owner_id"`
	TtlExpiresAt pgtype.Timestamptz `json:"ttl_expires_at"`
}

func (q *Queries) ClaimCalendar(ctx context.Context, arg ClaimCalendarParams) (CalendarLink, error) {
	row := q.db.QueryRow(ctx, claimCalendar, arg.ID, arg.OwnerID, arg.TtlExpiresAt)
	var i CalendarLink
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.OwnerID,
		&i.Name,
		&i.Description,
		&i.IsPublic,
		&i.AccessCount,
		&i.LastAccessedAt,
		&i.TtlExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Lang,
		&i.FormatEventTitles,
	)
	return i, err
}

const createCalendarCourse = `-- name: CreateCalendarCourse :one
INSERT INTO calendar_courses (calendar_id, curriculum_id, position)
VALUES ($1, $2, $3)
RETURNING id, calendar_id, curriculum_id, position, created_at
`

type CreateCalendarCourseParams struct {
	CalendarID   pgtype.UUID `json:"calendar_id"`
	CurriculumID pgtype.UUID `json:"curriculum_id"`
	Position     int16       `json:"position"`
}

func (q *Queries) CreateCalendarCourse(ctx context.Context, arg CreateCalendarCourseParams) (CalendarCourse, error) {
	row := q.db.QueryRow(ctx, createCalendarCourse, arg.CalendarID, arg.CurriculumID, arg.Position)
	var i CalendarCourse
	err := row.Scan(
		&i.ID,
		&i.CalendarID,
		&i.CurriculumID,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}

const createCalendarLink = `-- name: CreateCalendarLink :one
INSERT INTO calendar_links (slug, owner_id, name, description, lang, ttl_expires_at, format_event_titles)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, slug, owner_id, name, description, is_public, access_count, last_accessed_at, ttl_expires_at, created_at, updated_at, lang, format_event_titles
`

type CreateCalendarLinkParams struct {
	Slug              string             `json:"slug"`
	OwnerID           pgtype.UUID        `json:"owner_id"`
	Name              string             `json:"name"`
	Description       pgtype.Text        `json:"description"`
	Lang              string             `json:"lang"`
	TtlExpiresAt      pgtype.Timestamptz `json:"ttl_expires_at"`
	FormatEventTitles bool               `json:"format_event_titles"`
}

func (q *Queries) CreateCalendarLink(ctx context.Context, arg CreateCalendarLinkParams) (CalendarLink, error) {
	row := q.db.QueryRow(ctx, createCalendarLink,
		arg.Slug,
		arg.OwnerID,
		arg.Name,
		arg.Description,
		arg.Lang,
		arg.TtlExpiresAt,
		arg.FormatEventTitles,
	)
	var i CalendarLink
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.OwnerID,
		&i.Name,
		&i.Description,
		&i.IsPublic,
		&i.AccessCount,
		&i.LastAccessedAt,
		&i.TtlExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Lang,
		&i.FormatEventTitles,
	)
	return i, err
}

const createCalendarSubject = `-- name: CreateCalendarSubject :exec
INSERT INTO calendar_subjects (calendar_course_id, subject_id)
VALUES ($1, $2)
`

type CreateCalendarSubjectParams struct {
	CalendarCourseID pgtype.UUID `json:"calendar_course_id"`
	SubjectID        pgtype.UUID `json:"subject_id"`
}

func (q *Queries) CreateCalendarSubject(ctx context.Context, arg CreateCalendarSubjectParams) error {
	_, err := q.db.Exec(ctx, createCalendarSubject, arg.CalendarCourseID, arg.SubjectID)
	return err
}

const deleteCalendar = `-- name: DeleteCalendar :exec
DELETE FROM calendar_links WHERE id = $1
`

func (q *Queries) DeleteCalendar(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteCalendar, id)
	return err
}

const deleteCalendarCoursesByCalendar = `-- name: DeleteCalendarCoursesByCalendar :exec
DELETE FROM calendar_courses WHERE calendar_id = $1
`

func (q *Queries) DeleteCalendarCoursesByCalendar(ctx context.Context, calendarID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteCalendarCoursesByCalendar, calendarID)
	return err
}

const extendTTL = `-- name: ExtendTTL :exec
UPDATE calendar_links
SET ttl_expires_at = $2
WHERE id = $1
`

type ExtendTTLParams struct {
	ID           pgtype.UUID        `json:"id"`
	TtlExpiresAt pgtype.Timestamptz `json:"ttl_expires_at"`
}

func (q *Queries) ExtendTTL(ctx context.Context, arg ExtendTTLParams) error {
	_, err := q.db.Exec(ctx, extendTTL, arg.ID, arg.TtlExpiresAt)
	return err
}

const getActiveCalendarsCount = `-- name: GetActiveCalendarsCount :one
SELECT COUNT(*)::integer AS total FROM calendar_links WHERE ttl_expires_at > NOW()
`

func (q *Queries) GetActiveCalendarsCount(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, getActiveCalendarsCount)
	var total int32
	err := row.Scan(&total)
	return total, err
}

const getCalendarByID = `-- name: GetCalendarByID :one
SELECT id, slug, owner_id, name, description, is_public, access_count, last_accessed_at, ttl_expires_at, created_at, updated_at, lang, format_event_titles FROM calendar_links WHERE id = $1
`

func (q *Queries) GetCalendarByID(ctx context.Context, id pgtype.UUID) (CalendarLink, error) {
	row := q.db.QueryRow(ctx, getCalendarByID, id)
	var i CalendarLink
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.OwnerID,
		&i.Name,
		&i.Description,
		&i.IsPublic,
		&i.AccessCount,
		&i.LastAccessedAt,
		&i.TtlExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Lang,
		&i.FormatEventTitles,
	)
	return i, err
}

const getCalendarBySlug = `-- name: GetCalendarBySlug :one
SELECT id, slug, owner_id, name, description, is_public, access_count, last_accessed_at, ttl_expires_at, created_at, updated_at, lang, format_event_titles FROM calendar_links WHERE slug = $1
`

func (q *Queries) GetCalendarBySlug(ctx context.Context, slug string) (CalendarLink, error) {
	row := q.db.QueryRow(ctx, getCalendarBySlug, slug)
	var i CalendarLink
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.OwnerID,
		&i.Name,
		&i.Description,
		&i.IsPublic,
		&i.AccessCount,
		&i.LastAccessedAt,
		&i.TtlExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Lang,
		&i.FormatEventTitles,
	)
	return i, err
}

const getCalendarCoursesWithDetails = `-- name: GetCalendarCoursesWithDetails :many
SELECT
    cc.id AS calendar_course_id,
    cc.curriculum_id,
    cc.position,
    cur.code AS curriculum_code,
    cur.academic_year,
    cur.label AS curriculum_label,
    c.id AS course_id,
    c.title_it AS course_title_it,
    c.title_en AS course_title_en
FROM calendar_courses cc
JOIN curricula cur ON cur.id = cc.curriculum_id
JOIN courses c ON c.id = cur.course_id
WHERE cc.calendar_id = $1
ORDER BY cc.position
`

type GetCalendarCoursesWithDetailsRow struct {
	CalendarCourseID pgtype.UUID `json:"calendar_course_id"`
	CurriculumID     pgtype.UUID `json:"curriculum_id"`
	Position         int16       `json:"position"`
	CurriculumCode   string      `json:"curriculum_code"`
	AcademicYear     int16       `json:"academic_year"`
	CurriculumLabel  string      `json:"curriculum_label"`
	CourseID         pgtype.UUID `json:"course_id"`
	CourseTitleIt    string      `json:"course_title_it"`
	CourseTitleEn    pgtype.Text `json:"course_title_en"`
}

func (q *Queries) GetCalendarCoursesWithDetails(ctx context.Context, calendarID pgtype.UUID) ([]GetCalendarCoursesWithDetailsRow, error) {
	rows, err := q.db.Query(ctx, getCalendarCoursesWithDetails, calendarID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCalendarCoursesWithDetailsRow{}
	for rows.Next() {
		var i GetCalendarCoursesWithDetailsRow
		if err := rows.Scan(
			&i.CalendarCourseID,
			&i.CurriculumID,
			&i.Position,
			&i.CurriculumCode,
			&i.AcademicYear,
			&i.CurriculumLabel,
			&i.CourseID,
			&i.CourseTitleIt,
			&i.CourseTitleEn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCalendarSubjects = `-- name: GetCalendarSubjects :many
SELECT
    cs.calendar_course_id,
    s.id AS subject_id,
    s.title,
    s.module_code,
    s.credits,
    s.professor
FROM calendar_subjects cs
JOIN subjects s ON s.id = cs.subject_id
WHERE cs.calendar_course_id = ANY($1::uuid[])
ORDER BY s.title
`

type GetCalendarSubjectsRow struct {
	CalendarCourseID pgtype.UUID `json:"calendar_course_id"`
	SubjectID        pgtype.UUID `json:"subject_id"`
	Title            string      `json:"title"`
	ModuleCode       pgtype.Text `json:"module_code"`
	Credits          pgtype.Int2 `json:"credits"`
	Professor        pgtype.Text `json:"professor"`
}

func (q *Queries) GetCalendarSubjects(ctx context.Context, dollar_1 []pgtype.UUID) ([]GetCalendarSubjectsRow, error) {
	rows, err := q.db.Query(ctx, getCalendarSubjects, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCalendarSubjectsRow{}
	for rows.Next() {
		var i GetCalendarSubjectsRow
		if err := rows.Scan(
			&i.CalendarCourseID,
			&i.SubjectID,
			&i.Title,
			&i.ModuleCode,
			&i.Credits,
			&i.Professor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const incrementAccess = `-- name: IncrementAccess :exec
UPDATE calendar_links
SET access_count = access_count + 1, last_accessed_at = NOW()
WHERE id = $1
`

func (q *Queries) IncrementAccess(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, incrementAccess, id)
	return err
}

const listCalendarsByOwner = `-- name: ListCalendarsByOwner :many
SELECT
    cl.id, cl.slug, cl.owner_id, cl.name, cl.description, cl.is_public, cl.access_count, cl.last_accessed_at, cl.ttl_expires_at, cl.created_at, cl.updated_at, cl.lang, cl.format_event_titles,
    (SELECT COUNT(*) FROM calendar_courses WHERE calendar_id = cl.id) AS courses_count
FROM calendar_links cl
WHERE cl.owner_id = $1
ORDER BY cl.created_at DESC
`

type ListCalendarsByOwnerRow struct {
	ID                pgtype.UUID        `json:"id"`
	Slug              string             `json:"slug"`
	OwnerID           pgtype.UUID        `json:"owner_id"`
	Name              string             `json:"name"`
	Description       pgtype.Text        `json:"description"`
	IsPublic          bool               `json:"is_public"`
	AccessCount       int32              `json:"access_count"`
	LastAccessedAt    pgtype.Timestamptz `json:"last_accessed_at"`
	TtlExpiresAt      pgtype.Timestamptz `json:"ttl_expires_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	Lang              string             `json:"lang"`
	FormatEventTitles bool               `json:"format_event_titles"`
	CoursesCount      int64              `json:"courses_count"`
}

func (q *Queries) ListCalendarsByOwner(ctx context.Context, ownerID pgtype.UUID) ([]ListCalendarsByOwnerRow, error) {
	rows, err := q.db.Query(ctx, listCalendarsByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCalendarsByOwnerRow{}
	for rows.Next() {
		var i ListCalendarsByOwnerRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.OwnerID,
			&i.Name,
			&i.Description,
			&i.IsPublic,
			&i.AccessCount,
			&i.LastAccessedAt,
			&i.TtlExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Lang,
			&i.FormatEventTitles,
			&i.CoursesCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCalendarFields = `-- name: UpdateCalendarFields :one
UPDATE calendar_links
SET name = COALESCE(NULLIF($1::text, ''), name),
    description = COALESCE($2::text, description),
    lang = COALESCE(NULLIF($3::text, ''), lang),
    format_event_titles = COALESCE($4::boolean, format_event_titles),
    updated_at = NOW()
WHERE id = $5
RETURNING id, slug, owner_id, name, description, is_public, access_count, last_accessed_at, ttl_expires_at, created_at, updated_at, lang, format_event_titles
`

type UpdateCalendarFieldsParams struct {
	Name              pgtype.Text `json:"name"`
	Description       pgtype.Text `json:"description"`
	Lang              pgtype.Text `json:"lang"`
	FormatEventTitles pgtype.Bool `json:"format_event_titles"`
	ID                pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateCalendarFields(ctx context.Context, arg UpdateCalendarFieldsParams) (CalendarLink, error) {
	row := q.db.QueryRow(ctx, updateCalendarFields,
		arg.Name,
		arg.Description,
		arg.Lang,
		arg.FormatEventTitles,
		arg.ID,
	)
	var i CalendarLink
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.OwnerID,
		&i.Name,
		&i.Description,
		&i.IsPublic,
		&i.AccessCount,
		&i.LastAccessedAt,
		&i.TtlExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Lang,
		&i.FormatEventTitles,
	)
	return i, err
}
