// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: events.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countCalendarsByOwner = `-- name: CountCalendarsByOwner :one
SELECT COUNT(*)::integer AS total
FROM calendar_links
WHERE owner_id = $1
`

func (q *Queries) CountCalendarsByOwner(ctx context.Context, ownerID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countCalendarsByOwner, ownerID)
	var total int32
	err := row.Scan(&total)
	return total, err
}

const countEventsForCalendar = `-- name: CountEventsForCalendar :one
SELECT COUNT(*)::integer AS total
FROM timetable_events te
WHERE te.subject_id IN (
    SELECT cs.subject_id
    FROM calendar_subjects cs
    JOIN calendar_courses cc ON cc.id = cs.calendar_course_id
    WHERE cc.calendar_id = $1
)
`

func (q *Queries) CountEventsForCalendar(ctx context.Context, calendarID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countEventsForCalendar, calendarID)
	var total int32
	err := row.Scan(&total)
	return total, err
}

const getEventsForCalendar = `-- name: GetEventsForCalendar :many
SELECT
    te.id AS timetable_event_id,
    te.title,
    te.start_datetime,
    te.end_datetime,
    te.professor,
    te.module_code,
    te.credits,
    te.is_remote,
    te.teams_link,
    te.notes,
    te.group_id,
    0::integer AS sequence,
    c.name AS classroom_name,
    c.address AS classroom_address,
    c.latitude,
    c.longitude
FROM timetable_events te
LEFT JOIN classrooms c ON c.id = te.classroom_id
WHERE te.subject_id IN (
    SELECT cs.subject_id
    FROM calendar_subjects cs
    JOIN calendar_courses cc ON cc.id = cs.calendar_course_id
    WHERE cc.calendar_id = $1
)
ORDER BY te.start_datetime
`

type GetEventsForCalendarRow struct {
	TimetableEventID pgtype.UUID        `json:"timetable_event_id"`
	Title            string             `json:"title"`
	StartDatetime    pgtype.Timestamptz `json:"start_datetime"`
	EndDatetime      pgtype.Timestamptz `json:"end_datetime"`
	Professor        pgtype.Text        `json:"professor"`
	ModuleCode       pgtype.Text        `json:"module_code"`
	Credits          pgtype.Numeric     `json:"credits"`
	IsRemote         bool               `json:"is_remote"`
	TeamsLink        pgtype.Text        `json:"teams_link"`
	Notes            pgtype.Text        `json:"notes"`
	GroupID          pgtype.Text        `json:"group_id"`
	Sequence         int32              `json:"sequence"`
	ClassroomName    pgtype.Text        `json:"classroom_name"`
	ClassroomAddress pgtype.Text        `json:"classroom_address"`
	Latitude         pgtype.Numeric     `json:"latitude"`
	Longitude        pgtype.Numeric     `json:"longitude"`
}

func (q *Queries) GetEventsForCalendar(ctx context.Context, calendarID pgtype.UUID) ([]GetEventsForCalendarRow, error) {
	rows, err := q.db.Query(ctx, getEventsForCalendar, calendarID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetEventsForCalendarRow{}
	for rows.Next() {
		var i GetEventsForCalendarRow
		if err := rows.Scan(
			&i.TimetableEventID,
			&i.Title,
			&i.StartDatetime,
			&i.EndDatetime,
			&i.Professor,
			&i.ModuleCode,
			&i.Credits,
			&i.IsRemote,
			&i.TeamsLink,
			&i.Notes,
			&i.GroupID,
			&i.Sequence,
			&i.ClassroomName,
			&i.ClassroomAddress,
			&i.Latitude,
			&i.Longitude,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTotalEventsCount = `-- name: GetTotalEventsCount :one
SELECT COUNT(DISTINCT te.id)::bigint AS total
FROM timetable_events te
WHERE te.subject_id IN (
    SELECT cs.subject_id
    FROM calendar_subjects cs
)
`

func (q *Queries) GetTotalEventsCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, getTotalEventsCount)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const getUserEventStats = `-- name: GetUserEventStats :one
SELECT
    COUNT(*)::integer AS events_count,
    COALESCE(SUM(EXTRACT(EPOCH FROM (te.end_datetime - te.start_datetime)) / 3600), 0)::double precision AS total_hours
FROM timetable_events te
WHERE te.subject_id IN (
    SELECT cs.subject_id
    FROM calendar_subjects cs
    JOIN calendar_courses cc ON cc.id = cs.calendar_course_id
    JOIN calendar_links cl ON cl.id = cc.calendar_id
    WHERE cl.owner_id = $1
)
  AND te.start_datetime >= $2
  AND te.start_datetime < $3
`

type GetUserEventStatsParams struct {
	OwnerID         pgtype.UUID        `json:"owner_id"`
	StartDatetime   pgtype.Timestamptz `json:"start_datetime"`
	StartDatetime_2 pgtype.Timestamptz `json:"start_datetime_2"`
}

type GetUserEventStatsRow struct {
	EventsCount int32   `json:"events_count"`
	TotalHours  float64 `json:"total_hours"`
}

func (q *Queries) GetUserEventStats(ctx context.Context, arg GetUserEventStatsParams) (GetUserEventStatsRow, error) {
	row := q.db.QueryRow(ctx, getUserEventStats, arg.OwnerID, arg.StartDatetime, arg.StartDatetime_2)
	var i GetUserEventStatsRow
	err := row.Scan(&i.EventsCount, &i.TotalHours)
	return i, err
}

const getUserNextEvent = `-- name: GetUserNextEvent :one
SELECT
    te.title,
    te.start_datetime,
    te.end_datetime
FROM timetable_events te
WHERE te.subject_id IN (
    SELECT cs.subject_id
    FROM calendar_subjects cs
    JOIN calendar_courses cc ON cc.id = cs.calendar_course_id
    JOIN calendar_links cl ON cl.id = cc.calendar_id
    WHERE cl.owner_id = $1
)
  AND te.start_datetime >= $2
ORDER BY te.start_datetime
LIMIT 1
`

type GetUserNextEventParams struct {
	OwnerID       pgtype.UUID        `json:"owner_id"`
	StartDatetime pgtype.Timestamptz `json:"start_datetime"`
}

type GetUserNextEventRow struct {
	Title         string             `json:"title"`
	StartDatetime pgtype.Timestamptz `json:"start_datetime"`
	EndDatetime   pgtype.Timestamptz `json:"end_datetime"`
}

func (q *Queries) GetUserNextEvent(ctx context.Context, arg GetUserNextEventParams) (GetUserNextEventRow, error) {
	row := q.db.QueryRow(ctx, getUserNextEvent, arg.OwnerID, arg.StartDatetime)
	var i GetUserNextEventRow
	err := row.Scan(&i.Title, &i.StartDatetime, &i.EndDatetime)
	return i, err
}
