// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: events.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countEventsForCalendar = `-- name: CountEventsForCalendar :one
SELECT COUNT(*)::integer AS total
FROM timetable_events te
WHERE te.subject_id IN (
    SELECT cs.subject_id
    FROM calendar_subjects cs
    JOIN calendar_courses cc ON cc.id = cs.calendar_course_id
    WHERE cc.calendar_id = $1
)
`

func (q *Queries) CountEventsForCalendar(ctx context.Context, calendarID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countEventsForCalendar, calendarID)
	var total int32
	err := row.Scan(&total)
	return total, err
}

const getEventsForCalendar = `-- name: GetEventsForCalendar :many
SELECT
    te.id AS timetable_event_id,
    te.title,
    te.start_datetime,
    te.end_datetime,
    te.professor,
    te.module_code,
    te.credits,
    te.is_remote,
    te.teams_link,
    te.notes,
    te.group_id,
    0::integer AS sequence,
    c.name AS classroom_name,
    c.address AS classroom_address,
    c.latitude,
    c.longitude
FROM timetable_events te
LEFT JOIN classrooms c ON c.id = te.classroom_id
WHERE te.subject_id IN (
    SELECT cs.subject_id
    FROM calendar_subjects cs
    JOIN calendar_courses cc ON cc.id = cs.calendar_course_id
    WHERE cc.calendar_id = $1
)
ORDER BY te.start_datetime
`

type GetEventsForCalendarRow struct {
	TimetableEventID pgtype.UUID        `json:"timetable_event_id"`
	Title            string             `json:"title"`
	StartDatetime    pgtype.Timestamptz `json:"start_datetime"`
	EndDatetime      pgtype.Timestamptz `json:"end_datetime"`
	Professor        pgtype.Text        `json:"professor"`
	ModuleCode       pgtype.Text        `json:"module_code"`
	Credits          pgtype.Numeric     `json:"credits"`
	IsRemote         bool               `json:"is_remote"`
	TeamsLink        pgtype.Text        `json:"teams_link"`
	Notes            pgtype.Text        `json:"notes"`
	GroupID          pgtype.Text        `json:"group_id"`
	Sequence         int32              `json:"sequence"`
	ClassroomName    pgtype.Text        `json:"classroom_name"`
	ClassroomAddress pgtype.Text        `json:"classroom_address"`
	Latitude         pgtype.Numeric     `json:"latitude"`
	Longitude        pgtype.Numeric     `json:"longitude"`
}

func (q *Queries) GetEventsForCalendar(ctx context.Context, calendarID pgtype.UUID) ([]GetEventsForCalendarRow, error) {
	rows, err := q.db.Query(ctx, getEventsForCalendar, calendarID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetEventsForCalendarRow{}
	for rows.Next() {
		var i GetEventsForCalendarRow
		if err := rows.Scan(
			&i.TimetableEventID,
			&i.Title,
			&i.StartDatetime,
			&i.EndDatetime,
			&i.Professor,
			&i.ModuleCode,
			&i.Credits,
			&i.IsRemote,
			&i.TeamsLink,
			&i.Notes,
			&i.GroupID,
			&i.Sequence,
			&i.ClassroomName,
			&i.ClassroomAddress,
			&i.Latitude,
			&i.Longitude,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTotalEventsCount = `-- name: GetTotalEventsCount :one
SELECT COUNT(DISTINCT te.id)::bigint AS total
FROM timetable_events te
WHERE te.subject_id IN (
    SELECT cs.subject_id
    FROM calendar_subjects cs
)
`

func (q *Queries) GetTotalEventsCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, getTotalEventsCount)
	var total int64
	err := row.Scan(&total)
	return total, err
}
