// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql/driver"
	"fmt"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type CourseType string

const (
	CourseTypeBachelor          CourseType = "Bachelor"
	CourseTypeMaster            CourseType = "Master"
	CourseTypeSingleCycleMaster CourseType = "SingleCycleMaster"
)

func (e *CourseType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CourseType(s)
	case string:
		*e = CourseType(s)
	default:
		return fmt.Errorf("unsupported scan type for CourseType: %T", src)
	}
	return nil
}

type NullCourseType struct {
	CourseType CourseType `json:"course_type"`
	Valid      bool       `json:"valid"` // Valid is true if CourseType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCourseType) Scan(value interface{}) error {
	if value == nil {
		ns.CourseType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CourseType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCourseType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CourseType), nil
}

type CalendarCourse struct {
	ID           pgtype.UUID        `json:"id"`
	CalendarID   pgtype.UUID        `json:"calendar_id"`
	CurriculumID pgtype.UUID        `json:"curriculum_id"`
	Position     int16              `json:"position"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type CalendarLink struct {
	ID                pgtype.UUID        `json:"id"`
	Slug              string             `json:"slug"`
	OwnerID           pgtype.UUID        `json:"owner_id"`
	Name              string             `json:"name"`
	Description       pgtype.Text        `json:"description"`
	IsPublic          bool               `json:"is_public"`
	AccessCount       int32              `json:"access_count"`
	LastAccessedAt    pgtype.Timestamptz `json:"last_accessed_at"`
	TtlExpiresAt      pgtype.Timestamptz `json:"ttl_expires_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	Lang              string             `json:"lang"`
	FormatEventTitles bool               `json:"format_event_titles"`
}

type CalendarSubject struct {
	ID               pgtype.UUID        `json:"id"`
	CalendarCourseID pgtype.UUID        `json:"calendar_course_id"`
	SubjectID        pgtype.UUID        `json:"subject_id"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type CalendarSubscription struct {
	ID            pgtype.UUID        `json:"id"`
	CalendarID    pgtype.UUID        `json:"calendar_id"`
	UserAgent     pgtype.Text        `json:"user_agent"`
	IpHash        pgtype.Text        `json:"ip_hash"`
	LastRequestAt pgtype.Timestamptz `json:"last_request_at"`
	RequestCount  int32              `json:"request_count"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type Classroom struct {
	ID        pgtype.UUID    `json:"id"`
	Name      string         `json:"name"`
	Address   pgtype.Text    `json:"address"`
	Latitude  pgtype.Numeric `json:"latitude"`
	Longitude pgtype.Numeric `json:"longitude"`
}

type Course struct {
	ID            pgtype.UUID        `json:"id"`
	UniboID       int32              `json:"unibo_id"`
	CourseType    CourseType         `json:"course_type"`
	Campus        pgtype.Text        `json:"campus"`
	Languages     []string           `json:"languages"`
	DurationYears pgtype.Int2        `json:"duration_years"`
	Url           pgtype.Text        `json:"url"`
	Area          pgtype.Text        `json:"area"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	TitleIt       string             `json:"title_it"`
	TitleEn       pgtype.Text        `json:"title_en"`
	IsActive      bool               `json:"is_active"`
}

type Curricula struct {
	ID                 pgtype.UUID        `json:"id"`
	CourseID           pgtype.UUID        `json:"course_id"`
	Code               string             `json:"code"`
	AcademicYear       int16              `json:"academic_year"`
	Label              string             `json:"label"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	IsActive           bool               `json:"is_active"`
	TimetableHash      pgtype.Text        `json:"timetable_hash"`
	TimetableUpdatedAt pgtype.Timestamptz `json:"timetable_updated_at"`
}

type LoginHistory struct {
	ID            pgtype.UUID        `json:"id"`
	UserID        pgtype.UUID        `json:"user_id"`
	OauthProvider pgtype.Text        `json:"oauth_provider"`
	IpAddress     *netip.Addr        `json:"ip_address"`
	UserAgent     pgtype.Text        `json:"user_agent"`
	Success       bool               `json:"success"`
	FailureReason pgtype.Text        `json:"failure_reason"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type OauthProvider struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	Provider   string             `json:"provider"`
	ProviderID string             `json:"provider_id"`
	Email      pgtype.Text        `json:"email"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type RefreshToken struct {
	ID            pgtype.UUID        `json:"id"`
	UserID        pgtype.UUID        `json:"user_id"`
	TokenHash     string             `json:"token_hash"`
	FamilyID      pgtype.UUID        `json:"family_id"`
	ParentID      pgtype.UUID        `json:"parent_id"`
	IpAddress     *netip.Addr        `json:"ip_address"`
	UserAgent     pgtype.Text        `json:"user_agent"`
	DeviceName    pgtype.Text        `json:"device_name"`
	ExpiresAt     pgtype.Timestamptz `json:"expires_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UsedAt        pgtype.Timestamptz `json:"used_at"`
	RevokedAt     pgtype.Timestamptz `json:"revoked_at"`
	RevokedReason pgtype.Text        `json:"revoked_reason"`
}

type Role struct {
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Subject struct {
	ID           pgtype.UUID        `json:"id"`
	CurriculumID pgtype.UUID        `json:"curriculum_id"`
	Title        string             `json:"title"`
	ModuleCode   pgtype.Text        `json:"module_code"`
	GroupID      pgtype.Text        `json:"group_id"`
	Credits      pgtype.Int2        `json:"credits"`
	Professor    pgtype.Text        `json:"professor"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	IsActive     bool               `json:"is_active"`
}

type TimetableEvent struct {
	ID            pgtype.UUID        `json:"id"`
	SubjectID     pgtype.UUID        `json:"subject_id"`
	Title         string             `json:"title"`
	StartDatetime pgtype.Timestamptz `json:"start_datetime"`
	EndDatetime   pgtype.Timestamptz `json:"end_datetime"`
	Professor     pgtype.Text        `json:"professor"`
	ModuleCode    pgtype.Text        `json:"module_code"`
	Credits       pgtype.Numeric     `json:"credits"`
	ClassroomID   pgtype.UUID        `json:"classroom_id"`
	IsRemote      bool               `json:"is_remote"`
	TeamsLink     pgtype.Text        `json:"teams_link"`
	Notes         pgtype.Text        `json:"notes"`
	GroupID       pgtype.Text        `json:"group_id"`
	ContentHash   string             `json:"content_hash"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID          pgtype.UUID        `json:"id"`
	Email       string             `json:"email"`
	DisplayName pgtype.Text        `json:"display_name"`
	AvatarUrl   pgtype.Text        `json:"avatar_url"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	LastLogin   pgtype.Timestamptz `json:"last_login"`
}

type UserRole struct {
	UserID    pgtype.UUID        `json:"user_id"`
	RoleID    pgtype.UUID        `json:"role_id"`
	GrantedAt pgtype.Timestamptz `json:"granted_at"`
	GrantedBy pgtype.UUID        `json:"granted_by"`
}
