// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: subscriptions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const upsertSubscription = `-- name: UpsertSubscription :exec
INSERT INTO calendar_subscriptions (calendar_id, user_agent, ip_hash)
VALUES ($1, $2, $3)
ON CONFLICT (calendar_id, ip_hash) WHERE ip_hash IS NOT NULL
DO UPDATE SET
    last_request_at = NOW(),
    request_count = calendar_subscriptions.request_count + 1,
    user_agent = EXCLUDED.user_agent
`

type UpsertSubscriptionParams struct {
	CalendarID pgtype.UUID `json:"calendar_id"`
	UserAgent  pgtype.Text `json:"user_agent"`
	IpHash     pgtype.Text `json:"ip_hash"`
}

func (q *Queries) UpsertSubscription(ctx context.Context, arg UpsertSubscriptionParams) error {
	_, err := q.db.Exec(ctx, upsertSubscription, arg.CalendarID, arg.UserAgent, arg.IpHash)
	return err
}
